### ISSUE TITLE
Priam error on Cassandra start

### ISSUE THREAD

**Issue by jhohertz** [viafoura/deprecated-buri#28]
Priam is reporting an errant error when starting Cassandra.

It does in fact start, but since the script is waiting for it to launch, it's taking longer than the 5 seconds Priam is allowing for it to come back.

Two possible fixes:

1) Patch SCRIPT_EXECUTE_WAIT_TIME_MS in Priam to be more tolerant
2) Stop using the init script for C*... just use the stuff in cassandra's bin folder, which does not do as much waiting around, and is probably what Priam is expecting to execute generally.

Error for reference is:

```
2014-07-24 15:27:11.0069 INFO main com.netflix.priam.defaultimpl.CassandraProcessManager Starting cassandra server ....Join ring=true
2014-07-24 15:27:11.0080 INFO main com.netflix.priam.defaultimpl.CassandraProcessManager Starting cassandra server ....
2014-07-24 15:27:16.0081 WARN main com.netflix.priam.defaultimpl.CassandraProcessManager Starting Cassandra has an error
java.lang.IllegalThreadStateException: process hasn't exited
        at java.lang.UNIXProcess.exitValue(UNIXProcess.java:270)
        at com.netflix.priam.defaultimpl.CassandraProcessManager.start(CassandraProcessManager.java:68)
        at com.netflix.priam.PriamServer.intialize(PriamServer.java:91)
```

**Comment by jhohertz** [comment]
I've not actually seen this again in 20 or so startups monitored now, it's possible some of the fixes made as this was logged addressed it.

Closing for now.
